name: Main branch CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  norminette:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4

    - name: Install norminette
      run: python3 -m pip install --upgrade pip setuptools && python3 -m pip install norminette

    - name: Running Norminette
      run: make norm

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Building Binaries
      run: make
